import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// User profile — fitness background, goals, equipment, limitations
export const userProfiles = sqliteTable("user_profiles", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull(),
  age: integer("age"),
  gender: text("gender"), // male | female | other | prefer_not_to_say
  fitnessLevel: text("fitness_level").notNull(), // beginner | intermediate | advanced
  primaryGoal: text("primary_goal").notNull(), // lose_weight | build_muscle | improve_endurance | increase_flexibility | general_fitness
  secondaryGoals: text("secondary_goals").notNull().default("[]"), // JSON array
  equipment: text("equipment").notNull().default("[]"), // JSON array: dumbbells | barbell | resistance_bands | pull_up_bar | kettlebell | none | full_gym
  limitations: text("limitations").notNull().default(""), // injuries or physical limitations
  weeklyAvailability: integer("weekly_availability").notNull().default(3), // days per week
  sessionDuration: integer("session_duration").notNull().default(45), // minutes
  onboardingComplete: integer("onboarding_complete", { mode: "boolean" }).notNull().default(false),
});

export const insertUserProfileSchema = createInsertSchema(userProfiles).omit({ id: true });
export type InsertUserProfile = z.infer<typeof insertUserProfileSchema>;
export type UserProfile = typeof userProfiles.$inferSelect;

// Workout plans generated by Tricia
export const workoutPlans = sqliteTable("workout_plans", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: integer("user_id").notNull(),
  weekNumber: integer("week_number").notNull().default(1),
  planData: text("plan_data").notNull(), // JSON: full weekly plan
  createdAt: integer("created_at").notNull(),
});

export const insertWorkoutPlanSchema = createInsertSchema(workoutPlans).omit({ id: true });
export type InsertWorkoutPlan = z.infer<typeof insertWorkoutPlanSchema>;
export type WorkoutPlan = typeof workoutPlans.$inferSelect;

// Individual workout sessions (completed)
export const workoutSessions = sqliteTable("workout_sessions", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: integer("user_id").notNull(),
  planId: integer("plan_id"),
  sessionName: text("session_name").notNull(),
  exercises: text("exercises").notNull(), // JSON array of exercises with sets/reps
  completedAt: integer("completed_at").notNull(),
  durationMinutes: integer("duration_minutes"),
  notes: text("notes").default(""),
  rpe: integer("rpe"), // rate of perceived exertion 1-10
});

export const insertWorkoutSessionSchema = createInsertSchema(workoutSessions).omit({ id: true });
export type InsertWorkoutSession = z.infer<typeof insertWorkoutSessionSchema>;
export type WorkoutSession = typeof workoutSessions.$inferSelect;

// Chat messages with Tricia
export const chatMessages = sqliteTable("chat_messages", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  userId: integer("user_id").notNull(),
  role: text("role").notNull(), // user | assistant
  content: text("content").notNull(),
  createdAt: integer("created_at").notNull(),
});

export const insertChatMessageSchema = createInsertSchema(chatMessages).omit({ id: true });
export type InsertChatMessage = z.infer<typeof insertChatMessageSchema>;
export type ChatMessage = typeof chatMessages.$inferSelect;
